# -*- coding: utf-8 -*-
"""0424_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1baf_7spEfq5cBDpQA1e4U5O_pPO2oXr_
"""

import matplotlib as plt

class Rectangle(object):
    
    def __init__(self, width, height, color):
        self.width = width
        self.height = height
        self.color = color 

    def add_width(self, w):
        self.width += w
        return(self.width)

    def add_height(self, h):
        self.height += h
        return(self.height)

    def change_color(self, c):
        self.color = c
        return(self.color)

    def drawRectangle(self):
        plt.pyplot.gca().add_patch(plt.pyplot.Rectangle((0,0), self.width, self.height, fc = self.color))
        plt.pyplot.axis('scaled')
        plt.pyplot.show()

rec = Rectangle(3, 4, 'blue')

rec.drawRectangle()

rec.add_width(3)

rec.add_height(1)

rec.change_color('red')

rec.drawRectangle()

