# -*- coding: utf-8 -*-
"""0427_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uqSdsf_Gs92osW4SccN5aTjuQssPkubB
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd

df = pd.read_csv('/content/gdrive/My Drive/TopSellingAlbums.csv')

df

df.iloc[[0, 2, 4, 5]]

df.loc[0]

df.loc[[1, 4]]

df.iloc[[1], [2]]

df[['Released']]

df1=df[df['Released']>1979]

df1

smalldatabase=df1[df1['Music Recording Sales (millions)']>24]

smalldatabase

smalldatabase.to_csv('/content/gdrive/My Drive/smalldatabase.csv')

smalldatabase['Genre']

